import assert from "node:assert/strict"
import { mkdtemp } from "node:fs/promises"
import { tmpdir } from "node:os"
import { join } from "node:path"
import test from "node:test"
import { createBundleArtifacts, parseBundle } from "../src/app/bundle.js"
import { createQaEvidenceFromWebAppSmoke, readQaEvidence, renderQaEvidenceReport, writeQaEvidence } from "../src/app/qa-evidence.js"
import { refreshBundleProofArtifacts, writeBundleArtifacts } from "../src/app/write.js"
import { checkGeneratedWebApp, renderWebAppCheck, renderWebAppSmoke, runGeneratedWebAppSmoke } from "../src/migration/webapp-check.js"
import { generateWebAppScaffold } from "../src/migration/webapp.js"

test("generates runnable web API scaffold around D3 resources", () => {
  const files = generateWebAppScaffold({
    account: "SALES",
    strategy: "strangler",
    resources: [{ file: "CUSTOMERS", resource: "customers", endpoints: [], fields: [{ name: "name", dictionaryId: "NAME", attribute: 1, type: "string", required: false, multivalue: false }] }],
    services: [],
    phases: [],
    risks: [],
  })
  assert.ok(files.some((file) => file.path === "package.json"))
  assert.ok(files.some((file) => file.path === "package.json" && file.content.includes("\"test\"")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/health")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/openapi.json")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/access-plan.json")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("x-d3code-role")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("D3 access denied")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("writeMutationJournal")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("mutation-journal.jsonl")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("rollback")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/terminal/send")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("parseTerminalScreen")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("D3CODE_TERMINAL_ENABLED")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("writeTerminalJournal")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("terminal-journal.jsonl")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("D3CODE_TERMINAL_RECORD_TRANSCRIPT")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("D3CustomersRepository")))
  assert.ok(files.some((file) => file.path === "src/d3-client.ts" && file.content.includes("D3CODE_D3_COMMAND")))
  assert.ok(files.some((file) => file.path === "src/d3-client.ts" && file.content.includes("D3CODE_ALLOW_WRITES")))
  assert.ok(files.some((file) => file.path === "src/d3-client.ts" && file.content.includes("mock-data.json")))
  assert.ok(files.some((file) => file.path === "public/index.html" && file.content.includes("D3 Migration")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/health")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/ui-plan.json")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/data-validation-plan.json")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/index-validation-plan.json")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/code-modernization-plan.json")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/screen-modernization-plan.json")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/terminal/send")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/ui-plan.json")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/data-validation-plan.json")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/index-validation-plan.json")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/code-modernization-plan.json")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/screen-modernization-plan.json")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/dashboard-data.json")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/proof-dashboard.json")))
  assert.ok(files.some((file) => file.path === "public/styles.css"))
  assert.ok(files.some((file) => file.path === "public/index.html" && file.content.includes("D3 Cockpit")))
  assert.ok(files.some((file) => file.path === "public/index.html" && file.content.includes("Proof")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("renderCockpit")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/dashboard-data.json")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("renderProofDashboard")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/proof-dashboard.json")))
  assert.ok(files.some((file) => file.path === "public/index.html" && file.content.includes("Baked Skills")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("renderSkillManifest")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/skill-manifest.json")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/reference-skill-audit.json")))
  assert.ok(files.some((file) => file.path === "public/reference-skill-audit.json" && file.content.includes("out-of-scope")))
  assert.ok(files.some((file) => file.path === "public/index.html" && file.content.includes("D3 Operations")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("renderOperations")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/subagent-prompts.json")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/live-operator-runbook.json")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("renderTerminalContract")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("/cockpit-terminal.json")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("Blocked Until")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("Command Plan")))
  assert.ok(files.some((file) => file.path === "public/app.js" && file.content.includes("PowerTerm Screen Parity")))
  assert.ok(files.some((file) => file.path === "public/data-validation-plan.json"))
  assert.ok(files.some((file) => file.path === "public/index-validation-plan.json"))
  assert.ok(files.some((file) => file.path === "public/code-modernization-plan.json"))
  assert.ok(files.some((file) => file.path === "public/screen-modernization-plan.json"))
  assert.ok(files.some((file) => file.path === "public/subagent-prompts.json" && file.content.includes("Evidence gate")))
  assert.ok(files.some((file) => file.path === "public/live-operator-runbook.json" && file.content.includes("live-d3-proof")))
  assert.ok(files.some((file) => file.path === "public/cockpit-terminal.json" && file.content.includes("PowerTerm")))
  assert.ok(files.some((file) => file.path === "public/cockpit-terminal.json" && file.content.includes("D3CODE_TERMINAL_ENABLED=1")))
  assert.ok(files.some((file) => file.path === "public/cockpit-terminal.json" && file.content.includes("compile-catalog")))
  assert.ok(files.some((file) => file.path === "src/server.ts" && file.content.includes("/cockpit-terminal.json")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("D3CODE_MOCK")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("/openapi.json")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("mock-data.json")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("mockData")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("freePort")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("createTcpServer")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("parseD3Ids")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("formatD3Record")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("access denied")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("/terminal/send")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("terminal-journal.jsonl")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("transcriptRedacted")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("/subagent-prompts.json")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("/live-operator-runbook.json")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("/reference-skill-audit.json")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("mutation-journal.jsonl")))
  assert.ok(files.some((file) => file.path === "test/api-smoke.test.mjs" && file.content.includes("JOURNAL-SMOKE")))
})

test("checks generated web API scaffold readiness", async () => {
  const dir = await mkdtemp(join(tmpdir(), "d3code-webapp-check-"))
  const bundle = parseBundle({
    account: "SALES",
    profile: "prod",
    files: [{ name: "CUSTOMERS", suggestedResource: "customers", dictionary: [{ id: "@ID", attribute: 0 }], records: [] }],
    programs: [],
  })
  await writeBundleArtifacts(dir, createBundleArtifacts(bundle), bundle)
  const screenPlan = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "screen-modernization-plan.md"), "utf8"))
  assert.match(screenPlan, /D3 Screen Modernization Plan: SALES/)
  const uiPlan = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "web-ui-plan.md"), "utf8"))
  assert.match(uiPlan, /D3 Web UI Plan: SALES/)
  const reconciliationPlan = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "reconciliation-plan.md"), "utf8"))
  assert.match(reconciliationPlan, /D3 Cutover Reconciliation Plan: SALES/)
  const accessPlan = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "access-plan.md"), "utf8"))
  assert.match(accessPlan, /D3 Access Plan: SALES/)
  const terminalContract = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "cockpit-terminal.md"), "utf8"))
  assert.match(terminalContract, /D3 Cockpit Terminal Contract/)
  assert.match(terminalContract, /UOPY typed adapter/)
  assert.match(terminalContract, /D3CODE_TERMINAL_ENABLED=1/)
  assert.match(terminalContract, /compile-catalog/)
  const connectorStrategy = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "d3-connector-strategy.md"), "utf8"))
  assert.match(connectorStrategy, /D3 Connector Strategy/)
  assert.match(connectorStrategy, /PowerTerm-style programs/)
  const publicUiPlan = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "public/ui-plan.json"), "utf8"))
  assert.match(publicUiPlan, /customers/)
  const publicDashboardData = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "public/dashboard-data.json"), "utf8"))
  assert.match(publicDashboardData, /CUSTOMERS/)
  assert.match(publicDashboardData, /nodes/)
  const publicProofDashboard = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "public/proof-dashboard.json"), "utf8"))
  assert.match(publicProofDashboard, /readiness/)
  assert.match(publicProofDashboard, /release/)
  const referenceSkillAudit = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "d3code-reference-skill-audit.json"), "utf8"))
  assert.match(referenceSkillAudit, /SKILL\.md/)
  assert.match(referenceSkillAudit, /out-of-scope/)
  const publicReferenceSkillAudit = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "public/reference-skill-audit.json"), "utf8"))
  assert.match(publicReferenceSkillAudit, /ready/)
  const subagentPrompts = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "subagent-prompts.md"), "utf8"))
  assert.match(subagentPrompts, /D3 Bundle Subagent Prompt Pack/)
  assert.match(subagentPrompts, /Evidence gate:/)
  const liveRunbook = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "live-operator-runbook.md"), "utf8"))
  assert.match(liveRunbook, /D3 Live Operator Runbook/)
  assert.match(liveRunbook, /live-proof-init/)
  assert.match(liveRunbook, /live-proof-manifest\.json/)
  assert.match(liveRunbook, /live-proof-check/)
  assert.match(liveRunbook, /--screen-command/)
  const publicSubagentPrompts = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "public/subagent-prompts.json"), "utf8"))
  assert.match(publicSubagentPrompts, /Evidence gate/)
  const publicLiveRunbook = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "public/live-operator-runbook.json"), "utf8"))
  assert.match(publicLiveRunbook, /live-d3-proof/)
  assert.match(publicLiveRunbook, /live-proof-manifest\.json/)
  const report = await checkGeneratedWebApp(dir)
  assert.equal(report.ready, true)
  assert.ok(report.items.some((item) => item.id === "health-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "openapi-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "package-test" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3-write-guard" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3-record-mapper" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3-record-attributes" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3-record-serializer" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "static-ui-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-index" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-health-fetch" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-plan" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "dashboard-data" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "dashboard-data-graph" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "dashboard-data-panels" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "proof-dashboard" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "proof-dashboard-readiness" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "proof-dashboard-completion" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "proof-dashboard-release" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-data-validation-plan" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-data-validation-items" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-index-validation-plan" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-index-validation-items" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-code-modernization-plan" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-code-modernization-items" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-screen-modernization-plan" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-screen-modernization-items" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-plan-rendering" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-dashboard-rendering" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-proof-rendering" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-validation-rendering" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-modernization-rendering" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-skill-manifest-rendering" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-operations-rendering" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-cockpit-terminal-rendering" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-connector-rendering" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "ui-plan-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "dashboard-data-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "proof-dashboard-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "validation-plan-routes" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "modernization-plan-routes" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "skill-manifest-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "operations-artifact-routes" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "cockpit-terminal-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "connector-strategy-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "access-plan-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "access-role-guard" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "mutation-journal" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "mutation-rollback-proof" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "terminal-send-route" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "terminal-screen-parser" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "terminal-journal" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "terminal-transcript-redaction" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "access-plan" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "access-plan-users" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "access-plan-grants" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "cockpit-terminal-contract" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-cockpit-terminal-contract" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "cockpit-terminal-uopy-risk" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "cockpit-terminal-send-policy" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "cockpit-terminal-command-plan" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "cockpit-terminal-screen-parity" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3-connector-strategy" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3-connector-strategy-layers" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3-connector-strategy-proof" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3code-skill-pack" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3code-skill-pack-modes" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3code-skill-pack-evidence" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3code-skill-manifest" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3code-skill-manifest-skills" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3code-skill-manifest-coverage" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3code-skill-manifest-references" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3code-skill-manifest-phases" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-skill-manifest" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3code-reference-skill-audit" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "d3code-reference-skill-audit-ready" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-reference-skill-audit" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-reference-skill-audit-ready" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "subagent-prompts" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "subagent-prompt-packets" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "subagent-prompt-boundaries" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-subagent-prompts" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-subagent-prompt-boundaries" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "live-operator-runbook" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "live-operator-runbook-phases" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "live-operator-runbook-evidence" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "live-operator-runbook-scaffold" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-live-operator-runbook" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "public-live-operator-runbook-evidence" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "live-proof-scaffold" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "live-proof-scaffold-manifest" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "live-proof-scaffold-profile-doctor" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "live-proof-scaffold-compile-catalog" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-test" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-health" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-openapi" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-public-artifacts" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-reference-skill-audit" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-operations-artifacts" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-validation-plans" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-modernization-plans" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-mock-data" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-free-port" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-record-roundtrip" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-access-denied" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-terminal-send" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-terminal-journal" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-cockpit-terminal" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-connector-strategy" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "api-smoke-mutation-journal" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "mock-data" && item.status === "ok"))
  assert.ok(report.items.some((item) => item.id === "resource-customers-routes" && item.status === "ok"))
  const dashboard = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "dashboard.html"), "utf8"))
  assert.match(dashboard, /D3 Dashboard/)
  assert.match(dashboard, /D3 Login/)
  assert.match(dashboard, /D3 Terminal/)
  assert.match(dashboard, /Baked Skills/)
  assert.match(dashboard, /Access/)
  assert.match(dashboard, /PowerTerm-aware screen buffer/)
  assert.match(dashboard, /D3 logical model/)
  assert.match(dashboard, /data-model/)
  assert.match(renderWebAppCheck(report), /Ready: yes/)
})

test("builds and smoke-tests generated web API scaffold", async () => {
  const dir = await mkdtemp(join(tmpdir(), "d3code-webapp-smoke-"))
  const bundle = parseBundle({
    account: "SALES",
    profile: "prod",
    files: [{ name: "CUSTOMERS", suggestedResource: "customers", dictionary: [{ id: "@ID", attribute: 0 }, { id: "NAME", attribute: 1 }], records: [{ id: "100", raw: "Alice" }], observedIndexes: ["NAME"] }],
    programs: [],
  })
  await writeBundleArtifacts(dir, createBundleArtifacts(bundle), bundle)
  const mockData = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "mock-data.json"), "utf8"))
  assert.match(mockData, /Alice/)
  const report = await runGeneratedWebAppSmoke(dir)
  assert.equal(report.ready, true)
  assert.ok(report.steps.some((step) => step.id === "typescript-build" && step.status === "ok"))
  assert.ok(report.steps.some((step) => step.id === "api-smoke-tests" && step.status === "ok"))
  assert.match(renderWebAppSmoke(report), /Ready: yes/)
})

test("records generated web API smoke proof as QA evidence", async () => {
  const dir = await mkdtemp(join(tmpdir(), "d3code-webapp-qa-evidence-"))
  const smoke = {
    root: dir,
    ready: true,
    steps: [
      { id: "typescript-build", status: "ok" as const, message: "generated TypeScript compiled" },
      { id: "api-smoke-tests", status: "ok" as const, message: "ran generated smoke test file(s)" },
    ],
  }
  const evidence = createQaEvidenceFromWebAppSmoke(smoke)
  assert.equal(evidence.ready, true)
  const written = await writeQaEvidence(dir, evidence)
  assert.ok(written.some((file) => file.endsWith("qa-evidence.json")))
  assert.ok(written.some((file) => file.endsWith("qa-evidence.md")))
  const loaded = await readQaEvidence(dir)
  assert.equal(loaded?.ready, true)
  assert.match(renderQaEvidenceReport(evidence), /D3 Migration QA Evidence/)
  assert.match(renderQaEvidenceReport(evidence), /api-smoke-tests/)
})

test("refreshes generated proof artifacts after QA evidence is recorded", async () => {
  const dir = await mkdtemp(join(tmpdir(), "d3code-refresh-proof-"))
  const bundle = parseBundle({
    account: "SALES",
    profile: "prod",
    files: [{ name: "CUSTOMERS", suggestedResource: "customers", dictionary: [{ id: "@ID", attribute: 0 }, { id: "NAME", attribute: 1 }], records: [{ id: "100", raw: "Alice" }], observedIndexes: ["NAME"] }],
    programs: [],
  })
  const artifacts = createBundleArtifacts(bundle)
  await writeBundleArtifacts(dir, artifacts, bundle)
  await writeQaEvidence(dir, createQaEvidenceFromWebAppSmoke({
    root: dir,
    ready: true,
    steps: [
      { id: "typescript-build", status: "ok", message: "generated TypeScript compiled" },
      { id: "api-smoke-tests", status: "ok", message: "ran generated smoke test file(s)" },
    ],
  }))
  const refreshed = await refreshBundleProofArtifacts(dir, artifacts, bundle)
  assert.ok(refreshed.written.some((file) => file.endsWith("migration-readiness.json")))
  assert.ok(refreshed.written.some((file) => file.endsWith("completion-audit.json")))
  assert.ok(refreshed.written.some((file) => file.endsWith("goal-evidence.json")))
  assert.ok(refreshed.written.some((file) => file.endsWith("release-report.json")))
  assert.ok(refreshed.written.some((file) => file.endsWith("proof-dashboard.json")))
  const evidence = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "goal-evidence.md"), "utf8"))
  const completion = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "completion-audit.md"), "utf8"))
  const release = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "release-report.md"), "utf8"))
  const proof = await import("node:fs/promises").then((fs) => fs.readFile(join(dir, "public/proof-dashboard.json"), "utf8"))
  assert.match(evidence, /qa-evidence=ready/)
  assert.match(completion, /qa-evidence:ok/)
  assert.match(release, /D3 Migration Release Report: SALES/)
  assert.match(release, /Rollback/)
  assert.match(proof, /qaEvidence/)
  assert.match(proof, /canary|blocked/)
})
