import type { BundleIdeReport } from "./ide-report.js"

function escapeHtml(input: string): string {
  return input.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;")
}

function jsonScript(id: string, value: unknown): string {
  return `<script id="${id}" type="application/json">${escapeHtml(JSON.stringify(value))}</script>`
}

export function renderIdeHtml(report: BundleIdeReport): string {
  return [
    "<!doctype html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    `<title>D3 IDE - ${escapeHtml(report.account)}</title>`,
    "<style>",
    "body{margin:0;font:14px/1.4 system-ui,-apple-system,Segoe UI,sans-serif;background:#101418;color:#eef2f4}",
    ".shell{display:grid;grid-template-columns:280px 1fr;min-height:100vh}",
    "aside{border-right:1px solid #2d3840;background:#151b20;padding:16px;overflow:auto}",
    "main{padding:16px;overflow:auto}",
    "h1,h2,h3{margin:0 0 10px} h1{font-size:22px} h2{font-size:16px;color:#a9c7d8}",
    ".login,.panel,.node{border:1px solid #2d3840;background:#182027;border-radius:8px;padding:12px;margin-bottom:12px}",
    "label{display:block;color:#9fb0ba;margin:8px 0 4px} input,select{box-sizing:border-box;width:100%;background:#0d1115;color:#eef2f4;border:1px solid #34444f;border-radius:6px;padding:8px}",
    "button{margin-top:10px;width:100%;border:0;border-radius:6px;padding:9px;background:#3f8cff;color:white;font-weight:700}",
    ".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}",
    ".graph{height:520px;border:1px solid #2d3840;border-radius:8px;background:#0d1115;position:relative;overflow:hidden;margin-bottom:12px}",
    ".node{position:absolute;min-width:120px;max-width:180px;margin:0;box-shadow:0 10px 30px #0008}",
    ".node small{display:block;color:#a6bac4}.ok{border-color:#3fa36b}.review{border-color:#d2aa4c}.warning{border-color:#e07837}.blocked{border-color:#d84f4f}",
    "svg{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}.edge{stroke:#5c7480;stroke-width:1.4}.edge-label{fill:#8fa7b2;font-size:11px}",
    "ul{margin:0;padding-left:18px}.muted{color:#9fb0ba}.pill{display:inline-block;border:1px solid #34444f;border-radius:999px;padding:2px 8px;margin:2px;color:#b8ced8}",
    "@media(max-width:760px){.shell{display:block}aside{border-right:0;border-bottom:1px solid #2d3840}.graph{height:720px}}",
    "</style>",
    "</head>",
    "<body>",
    '<div class="shell">',
    "<aside>",
    `<h1>D3 ${escapeHtml(report.account)}</h1>`,
    `<p class="muted">Profile: ${escapeHtml(report.profile)}</p>`,
    '<section class="login">',
    "<h2>D3 Login</h2>",
    "<label>Host / profile</label><input value=\"\" placeholder=\"prod or ssh host\">",
    "<label>Username</label><input autocomplete=\"username\">",
    "<label>Password</label><input type=\"password\" autocomplete=\"current-password\">",
    "<label>Account</label><input value=\"\" placeholder=\"D3 account\">",
    "<button type=\"button\">Connect</button>",
    '<p class="muted">Credentials are a UI placeholder here; D3 Code stores real secrets through keychain/env references.</p>',
    "</section>",
    '<section class="panel">',
    "<h2>D3 Terminal</h2>",
    "<label>Bridge mode</label><select><option>persistent PTY / SSH session</option><option>typed TCL command bridge</option><option>PowerTerm-aware screen buffer</option><option>Rocket MV BASIC IDE parity</option><option>UOPY typed adapter spike</option></select>",
    "<label>Command / keys</label><input placeholder=\"WHO, LIST MD, menu selection, or screen keys\">",
    "<button type=\"button\">Send</button>",
    '<p class="muted">The live IDE should attach to a persistent D3 session. Full-screen legacy programs need raw transcript plus screen-buffer proof because PowerTerm-style cursor behavior is not ordinary xterm output. Rocket MV BASIC docs are used as an IDE checklist for connected accounts, locks, hashed files, compile/catalog, diagnostics, and debugger boundaries.</p>',
    "</section>",
    '<section class="panel"><h2>Users</h2><ul>',
    ...(report.panels.find((panel) => panel.id === "users")?.items ?? ["Import from D3/Unix auth during live profile proof."]).map((item) => `<li>${escapeHtml(item)}</li>`),
    "</ul></section>",
    '<section class="panel"><h2>Access</h2><ul>',
    ...(report.panels.find((panel) => panel.id === "access")?.items ?? ["Map roles to screens before writes are enabled."]).map((item) => `<li>${escapeHtml(item)}</li>`),
    "</ul></section>",
    '<section class="panel"><h2>Baked Skills</h2><ul>',
    "<li>GSD, plan, audit, migrate, API, modernize, and QA modes travel with generated artifacts.</li>",
    "<li>Use <code>d3code-skill-manifest.json</code> or <code>public/skill-manifest.json</code> for machine-readable coverage.</li>",
    "</ul></section>",
    '<section class="panel"><h2>Next Commands</h2><ul>',
    ...report.nextCommands.map((command) => `<li><code>${escapeHtml(command)}</code></li>`),
    "</ul></section>",
    "</aside>",
    "<main>",
    '<section class="graph" id="graph"><svg id="edges"></svg></section>',
    '<section class="grid">',
    ...report.panels.map((panel) => [
      '<article class="panel">',
      `<h2>${escapeHtml(panel.title)}</h2>`,
      "<ul>",
      ...(panel.items.length ? panel.items.map((item) => `<li>${escapeHtml(item)}</li>`) : ["<li>none</li>"]),
      "</ul>",
      "</article>",
    ].join("")),
    "</section>",
    '<section class="panel"><h2>Node Inventory</h2>',
    ...["user", "file", "dictionary", "program", "subroutine", "index", "data-model", "screen"].map((kind) => [
      `<h3>${kind === "data-model" ? "D3 logical model" : kind}</h3>`,
      report.nodes.filter((node) => node.kind === kind).map((node) => `<span class="pill ${node.risk}">${escapeHtml(node.label)}</span>`).join("") || '<span class="muted">none</span>',
    ].join("")),
    "</section>",
    "</main>",
    "</div>",
    jsonScript("ide-data", report),
    "<script>",
    "const data=JSON.parse(document.getElementById('ide-data').textContent);",
    "const graph=document.getElementById('graph');const svg=document.getElementById('edges');",
    "const center={x:graph.clientWidth/2,y:graph.clientHeight/2};const radius=Math.max(160,Math.min(center.x,center.y)-80);",
    "const positions=new Map();data.nodes.forEach((node,i)=>{const angle=(Math.PI*2*i)/Math.max(1,data.nodes.length)-Math.PI/2;const x=center.x+Math.cos(angle)*radius;const y=center.y+Math.sin(angle)*radius;positions.set(node.id,{x,y});const el=document.createElement('div');el.className=`node ${node.risk}`;el.style.left=`${Math.max(8,Math.min(graph.clientWidth-190,x-70))}px`;el.style.top=`${Math.max(8,Math.min(graph.clientHeight-86,y-28))}px`;el.innerHTML=`<strong>${node.label}</strong><small>${node.kind}</small>`;graph.appendChild(el);});",
    "data.edges.forEach(edge=>{const a=positions.get(edge.from);const b=positions.get(edge.to);if(!a||!b)return;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('class','edge');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);svg.appendChild(line);});",
    "</script>",
    "</body>",
    "</html>",
  ].join("\n")
}
