import type { AdapterFile } from "./adapter.js"
import type { MigrationPlan } from "./planner.js"
import { createIdeTerminalContract } from "../d3/ide-terminal.js"
import { referenceSkillCoverageReady, referenceSkillFamilies } from "../skills/reference-map.js"

function pascal(resource: string): string {
  return resource
    .split(/[-_\s]+/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join("")
}

function routeEntries(plan: MigrationPlan): string[] {
  return plan.resources.map((resource) => {
    const name = pascal(resource.resource)
    return `  ${JSON.stringify(resource.resource)}: create${name}Routes(new D3${name}Repository(d3)),`
  })
}

function resourceManifest(plan: MigrationPlan): string {
  return JSON.stringify(plan.resources.map((resource) => ({
    resource: resource.resource,
    file: resource.file,
    fields: (resource.fields ?? []).map((field) => ({ name: field.name, dictionaryId: field.dictionaryId, attribute: field.attribute })),
  })), null, 2)
}

export function generateWebAppScaffold(plan: MigrationPlan): AdapterFile[] {
  const ideTerminalContract = createIdeTerminalContract({ name: "generated", type: "local", account: plan.account })
  const generatedDataValidationPlan = {
    account: plan.account,
    profile: "generated",
    items: plan.resources.flatMap((resource) => (resource.fields ?? []).map((field) => ({
      file: resource.file,
      status: field.multivalue || field.type === "number" || field.type === "boolean" ? "review" : "ok",
      subject: `api-field:${field.name}`,
      rationale: field.multivalue
        ? `Generated API field ${field.name} preserves D3 multivalue shape; confirm ordered array semantics before enabling writes.`
        : `Generated API field ${field.name} keeps D3 dictionary attribution for validation.`,
      evidence: [`resource:${resource.resource}`, `dictionary:${field.dictionaryId}`, field.attribute !== undefined ? `attribute:${field.attribute}` : "attribute:unknown"],
      commands: [`LIST DICT ${resource.file} ${field.dictionaryId}`, "d3code bundle-data-plan d3-app-bundle.json"],
    }))),
  }
  const generatedIndexValidationPlan = {
    account: plan.account,
    profile: "generated",
    items: plan.resources.flatMap((resource) => (resource.fields ?? []).map((field) => ({
      file: resource.file,
      status: "review",
      index: field.dictionaryId,
      rationale: `Generated API field ${field.name} should be reconciled with D3 LIST-INDEX evidence before relying on list/search behavior.`,
      evidence: [`resource:${resource.resource}`, `field:${field.name}`, `dictionary:${field.dictionaryId}`],
      commands: [`LIST-INDEX ${resource.file}`, `LIST DICT ${resource.file} ${field.dictionaryId}`, "d3code bundle-index-plan d3-app-bundle.json"],
    }))),
  }
  const generatedCodeModernizationPlan = {
    account: plan.account,
    profile: "generated",
    items: plan.services.length
      ? plan.services.map((service) => ({
          program: service.program,
          priority: "P2",
          subject: "service-boundary",
          rationale: `Generated service ${service.suggestedService} wraps D3 BASIC/CALL behavior; confirm compile/catalog and side-effect proof before exposing writes.`,
          evidence: [`program:${service.program}`, `calls:${service.calls.join(",") || "none"}`, `opens:${service.opens.join(",") || "none"}`],
          commands: ["d3code bundle-code-plan d3-app-bundle.json", "d3code modernization-proof --before BP_ITEM.before.txt --after BP_ITEM.txt --compile-output compile-output.txt"],
          doneWhen: ["Compile/catalog proof exists for changed BASIC.", "CALL inputs, outputs, COMMON usage, and side effects are documented."],
        }))
      : [{
          program: "*",
          priority: "P2",
          subject: "capture-programs",
          rationale: "No BASIC services were included in the migration plan; capture representative programs before declaring modernization complete.",
          evidence: ["services:0"],
          commands: ["d3code bundle-capture --profile <profile> --account <account> --program-files BP --sample-limit 5 > d3-app-bundle.json"],
          doneWhen: ["Representative BASIC programs are captured or explicitly marked out of scope."],
        }],
  }
  const generatedScreenModernizationPlan = {
    account: plan.account,
    profile: "generated",
    items: plan.resources.map((resource) => ({
      program: resource.file,
      priority: "P2",
      risk: "medium",
      operations: [],
      rationale: `Generated web resource ${resource.resource} needs representative legacy terminal/menu evidence before UI parity is accepted.`,
      commands: ["d3code bundle-screen-plan d3-app-bundle.json", "d3code terminal-capture --profile <profile> --out ./terminal-proof '<screen command>'"],
      doneWhen: ["Representative terminal transcript is captured or the resource is marked screen-neutral.", "Every generated screen action is mapped back to D3 evidence."],
    })),
  }
  const generatedSubagentPrompts = {
    account: plan.account,
    profile: "generated",
    packets: [
      {
        id: "ide-terminal-proof",
        agent: "d3-operator",
        safety: "ask",
        title: "Prove the IDE terminal connector against the target D3 account",
        allowedTools: ["d3_detect", "d3_login", "d3_tcl", "terminal-capture", "screen-parse", "live-proof-check"],
        deniedActions: ["destructive TCL", "unreviewed writes", "PowerTerm parity claims without transcript and screen-buffer proof"],
        prompt: "Evidence gate: capture profile-doctor, terminal transcript, parsed screen buffer, operator notes, rollback notes, and compile/catalog proof before marking the IDE terminal live-ready.",
      },
      {
        id: "legacy-screen-modernization",
        agent: "d3-architect",
        safety: "plan",
        title: "Map D3/PowerTerm legacy screens into modern IDE workflows",
        allowedTools: ["screen-parse", "bundle-screen-plan", "bundle-ui-plan", "manual-search"],
        deniedActions: ["rewrite BASIC screen flows without live transcript evidence", "treat D3 files as SQL tables"],
        prompt: "Evidence gate: every proposed web screen field, action, cursor/input behavior, and validation rule must point back to captured D3 screen or dictionary evidence.",
      },
      {
        id: "data-integrity-audit",
        agent: "d3-data-mapper",
        safety: "ask",
        title: "Audit multivalue data shapes and inferred relationships",
        allowedTools: ["d3_list_files", "d3_read_dict", "d3_query_aql", "d3_index_account", "d3_search", "bundle-data-plan", "bundle-index-plan"],
        deniedActions: ["flatten multivalues without relationship review", "choose a migration database before the user selects one"],
        prompt: "Evidence gate: preserve D3 multivalue/subvalue ordering, dictionary attribution, and inferred relationships in the IDE; only create target-database mappings during explicit migration planning.",
      },
    ],
  }
  const generatedLiveRunbook = {
    account: plan.account,
    profile: "generated",
    liveProofDir: "./live-proof",
    assumptions: [
      "The generated IDE can render D3 terminal intent before a live account exists.",
      "Real terminal sends stay disabled until D3CODE_TERMINAL_ENABLED=1 and live proof is recorded.",
      "PowerTerm-style parity requires raw transcript, screen-buffer parsing, and operator approval.",
    ],
    phases: [
      {
        id: "live-d3-proof",
        title: "Prove the D3 profile and terminal account",
        commands: ["d3code live-proof-init live-proof --profile <profile> --account <account> --screen-command '<screen command>' --basic-file <file> --basic-item <item>", "d3code profile-doctor --profile <profile> --json > live-proof/profile-doctor.json", "d3code terminal-capture --profile <profile> --out live-proof '<screen command>'", "d3code live-proof-check live-proof"],
        evidence: ["live-proof-manifest.json", "profile-doctor.json", "terminal-transcript.txt", "screen-buffer.json", "operator-notes.md", "compile-catalog-transcript.txt", "rollback.md"],
      },
      {
        id: "generated-qa-proof",
        title: "Prove the generated IDE/API without a live D3 account",
        commands: ["d3code webapp-check ./migration-output", "d3code webapp-smoke ./migration-output --record", "npm run regression"],
        evidence: ["qa-evidence.json/md", "proof-data.json", "completion-audit.md", "regression output"],
      },
    ],
  }
  const generatedReferenceSkillAudit = {
    root: "generated-reference-map",
    ready: referenceSkillCoverageReady(),
    total: referenceSkillFamilies.length,
    items: referenceSkillFamilies.map((family) => ({
      path: `${family.source}:${family.reference}`,
      status: family.status,
      productSkills: family.productSkills,
      rationale: family.rationale,
    })),
  }
  const imports = plan.resources.flatMap((resource) => {
    const name = pascal(resource.resource)
    return [
      `import { D3${name}Repository } from "./${resource.resource}/${resource.resource}.repository.js"`,
      `import { create${name}Routes } from "./${resource.resource}/${resource.resource}.routes.js"`,
    ]
  })

  return [
    {
      path: "package.json",
      content: `${JSON.stringify({
        name: `${plan.account.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-d3-migration-api`,
        version: "0.1.0",
        type: "module",
        private: true,
        scripts: {
          build: "tsc -p tsconfig.json",
          test: "npm run build && node --test test/*.test.mjs",
          start: "node dist/server.js",
          dev: "tsc -p tsconfig.json && node dist/server.js",
        },
        devDependencies: {
          "@types/node": "^22.0.0",
          "typescript": "^5.0.0",
        },
      }, null, 2)}\n`,
    },
    {
      path: "tsconfig.json",
      content: `${JSON.stringify({
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          strict: true,
          esModuleInterop: true,
          outDir: "dist",
          rootDir: "src",
          skipLibCheck: true,
        },
        include: ["src/**/*.ts"],
      }, null, 2)}\n`,
    },
    {
      path: "README.md",
      content: [
        `# ${plan.account} D3 Migration API`,
        "",
        "Generated by D3 Code as a strangler-style web/API scaffold around the captured D3 resources.",
        "",
        "## Commands",
        "",
        "```bash",
        "npm install",
        "npm test",
        "npm run build",
        "D3CODE_MOCK=1 npm start",
        "```",
        "",
        "Open `http://localhost:3000/` for the generated browser shell or call `/health` and resource endpoints directly.",
        "",
        "Set `D3CODE_D3_COMMAND` to the local command that accepts TCL on stdin when connecting this scaffold to a real D3 account.",
        "Mutation endpoints are guarded by default. Set `D3CODE_ALLOW_WRITES=1` only after D3 lock, validation, rollback, and live-account proof are complete. Write calls also require an access role from `x-d3code-role` or `D3CODE_ACCESS_ROLE`; review-only D3 write/admin roles require `D3CODE_ACCESS_REVIEWED=1`.",
        "Every generated create/update route appends `mutation-journal.jsonl` with the action, D3 resource, item id, before/after payload where available, and an operator rollback note.",
        "The generated IDE terminal endpoint is `/terminal/send`. It is mock-safe by default; real D3 terminal sends require `D3CODE_TERMINAL_ENABLED=1` and risky TCL still goes through the write/access guard.",
        "",
        "## Generated Resources",
        ...plan.resources.map((resource) => `- ${resource.resource}: D3 file ${resource.file}`),
        "",
      ].join("\n"),
    },
    {
      path: "src/d3-client.ts",
      content: [
        "import { spawn } from \"node:child_process\"",
        "import { existsSync, readFileSync } from \"node:fs\"",
        "",
        "interface MockRecord { id: string; raw: string }",
        "type MockData = Record<string, MockRecord[]>",
        "",
        "export class D3Client {",
        "  private mockData?: MockData",
        "  constructor(private readonly command = process.env.D3CODE_D3_COMMAND ?? \"d3\") {}",
        "",
        "  private loadMockData(): MockData {",
        "    if (this.mockData) return this.mockData",
        "    const path = \"mock-data.json\"",
        "    this.mockData = existsSync(path) ? JSON.parse(readFileSync(path, \"utf8\")) as MockData : {}",
        "    return this.mockData",
        "  }",
        "",
        "  private mockTcl(command: string): string {",
        "    const data = this.loadMockData()",
        "    const select = command.match(/^\\s*SELECT\\s+([A-Z0-9_.-]+)/i)",
        "    if (select?.[1]) return (data[select[1].toUpperCase()] ?? data[select[1]] ?? []).map((record) => record.id).join(\"\\n\")",
        "    const ct = command.match(/^\\s*CT\\s+([A-Z0-9_.-]+)\\s+([^\\s]+)/i)",
        "    if (ct?.[1] && ct?.[2]) {",
        "      const records = data[ct[1].toUpperCase()] ?? data[ct[1]] ?? []",
        "      return records.find((record) => record.id === ct[2])?.raw ?? \"\"",
        "    }",
        "    return \"\"",
        "  }",
        "",
        "  private isMutation(command: string): boolean {",
        "    return /(^|\\n)\\s*(ED|COPY|DELETE|CLEAR-FILE|CREATE-FILE|RESIZE|UPDATE|WRITE|MATWRITE|FILEDELETE)\\b/i.test(command)",
        "  }",
        "",
        "  private assertAllowed(command: string): void {",
        "    if (process.env.D3CODE_MOCK === \"1\") return",
        "    if (this.isMutation(command) && process.env.D3CODE_ALLOW_WRITES !== \"1\") {",
        "      throw new Error(\"D3 mutation blocked. Set D3CODE_ALLOW_WRITES=1 only after lock, validation, rollback, and live-D3 proof are complete.\")",
        "    }",
        "  }",
        "",
        "  async tcl(command: string): Promise<string> {",
        "    this.assertAllowed(command)",
        "    if (process.env.D3CODE_MOCK === \"1\") return this.mockTcl(command)",
        "    return new Promise((resolve, reject) => {",
        "      const child = spawn(this.command, { shell: true, stdio: [\"pipe\", \"pipe\", \"pipe\"] })",
        "      let stdout = \"\"",
        "      let stderr = \"\"",
        "      child.stdout.on(\"data\", (chunk) => { stdout += chunk })",
        "      child.stderr.on(\"data\", (chunk) => { stderr += chunk })",
        "      child.on(\"error\", reject)",
        "      child.on(\"close\", (code) => {",
        "        if (code && code !== 0) reject(new Error(stderr || `D3 command exited ${code}`))",
        "        else resolve(stdout)",
        "      })",
        "      child.stdin.end(`${command}\\n`)",
        "    })",
        "  }",
        "}",
        "",
      ].join("\n"),
    },
    {
      path: "src/server.ts",
      content: [
        "import { createServer } from \"node:http\"",
        "import { appendFile, readFile } from \"node:fs/promises\"",
        "import { extname, join } from \"node:path\"",
        "import { D3Client } from \"./d3-client.js\"",
        ...imports,
        "",
        "const d3 = new D3Client()",
        "const routes = {",
        ...routeEntries(plan),
        "} as const",
        "",
        "function send(res: any, status: number, body: unknown) {",
        "  res.writeHead(status, { \"content-type\": \"application/json\" })",
        "  res.end(JSON.stringify(body))",
        "}",
        "",
        "async function sendStatic(res: any, path: string) {",
        "  const file = path === \"/\" ? \"index.html\" : path.replace(/^\\//, \"\")",
        "  const target = join(process.cwd(), \"public\", file)",
        "  const contentType = extname(target) === \".css\" ? \"text/css\" : extname(target) === \".js\" ? \"text/javascript\" : extname(target) === \".json\" ? \"application/json\" : \"text/html\"",
        "  const body = await readFile(target)",
        "  res.writeHead(200, { \"content-type\": contentType })",
        "  res.end(body)",
        "}",
        "",
        "async function readBody(req: any): Promise<unknown> {",
        "  const chunks: Buffer[] = []",
        "  for await (const chunk of req) chunks.push(Buffer.from(chunk))",
        "  const raw = Buffer.concat(chunks).toString(\"utf8\")",
        "  return raw ? JSON.parse(raw) : {}",
        "}",
        "",
        "interface AccessGrant { user?: string; role?: string; resource?: string; access?: string; status?: string }",
        "interface AccessPlan { users?: unknown[]; grants?: AccessGrant[]; warnings?: string[] }",
        "",
        "async function loadAccessPlan(): Promise<AccessPlan> {",
        "  try {",
        "    return JSON.parse(await readFile(join(process.cwd(), \"access-plan.json\"), \"utf8\")) as AccessPlan",
        "  } catch {",
        "    return { users: [], grants: [], warnings: [\"access-plan.json missing; mutation access is denied until a D3 access plan is bundled\"] }",
        "  }",
        "}",
        "",
        "function headerValue(req: any, name: string): string {",
        "  const value = req.headers?.[name.toLowerCase()]",
        "  return Array.isArray(value) ? value[0] ?? \"\" : value ?? \"\"",
        "}",
        "",
        "async function assertMutationAccess(req: any, resource: string): Promise<void> {",
        "  if (process.env.D3CODE_MOCK === \"1\") return",
        "  if (process.env.D3CODE_ALLOW_WRITES !== \"1\") {",
        "    throw new Error(\"D3 mutation blocked. Set D3CODE_ALLOW_WRITES=1 only after lock, validation, rollback, and live-D3 proof are complete.\")",
        "  }",
        "  if (process.env.D3CODE_BYPASS_ACCESS_PLAN === \"1\") return",
        "  const role = (headerValue(req, \"x-d3code-role\") || process.env.D3CODE_ACCESS_ROLE || \"\").trim()",
        "  const user = (headerValue(req, \"x-d3code-user\") || process.env.D3CODE_ACCESS_USER || \"\").trim()",
        "  if (!role) throw new Error(\"D3 access denied. Provide x-d3code-role or D3CODE_ACCESS_ROLE for mutation endpoints.\")",
        "  const plan = await loadAccessPlan()",
        "  const grants = (plan.grants ?? []).filter((grant) => {",
        "    const roleMatches = String(grant.role ?? \"\").toLowerCase() === role.toLowerCase()",
        "    const resourceMatches = String(grant.resource ?? \"\").toLowerCase() === resource.toLowerCase()",
        "    const userMatches = !user || !grant.user || String(grant.user).toLowerCase() === user.toLowerCase()",
        "    return roleMatches && resourceMatches && userMatches",
        "  })",
        "  if (grants.length === 0) throw new Error(`D3 access denied. Role ${role} has no mutation grant for ${resource}.`)",
        "  const writable = grants.find((grant) => grant.access === \"write-review\" || grant.access === \"admin-review\")",
        "  if (!writable) throw new Error(`D3 access denied. Role ${role} is read-only for ${resource}.`)",
        "  if (writable.status === \"review\" && process.env.D3CODE_ACCESS_REVIEWED !== \"1\") {",
        "    throw new Error(`D3 access denied. Role ${role} mutation grant for ${resource} is review-only until D3 safety, lock, rollback, and live-account proof are recorded.`)",
        "  }",
        "}",
        "",
        "async function writeMutationJournal(entry: { action: string; resource: string; id?: string; before?: unknown; after?: unknown }) {",
        "  const payload = {",
        "    at: new Date().toISOString(),",
        "    account: " + JSON.stringify(plan.account) + ",",
        "    ...entry,",
        "    rollback: entry.before ? \"restore before payload through the D3 terminal after lock/operator review\" : \"delete created item only after confirming no downstream D3 references were created\",",
        "  }",
        "  await appendFile(join(process.cwd(), \"mutation-journal.jsonl\"), `${JSON.stringify(payload)}\\n`)",
        "}",
        "",
        "function redactTerminalCommand(command: string): string {",
        "  if (/password|passwd|credential|secret/i.test(command)) return \"[redacted sensitive D3 terminal command]\"",
        "  return command",
        "}",
        "",
        "async function writeTerminalJournal(entry: { command: string; transcript: string; screen: { width: number; height: number; lines: string[]; events: unknown[] } }) {",
        "  const includeTranscript = process.env.D3CODE_TERMINAL_RECORD_TRANSCRIPT === \"1\"",
        "  const payload = {",
        "    at: new Date().toISOString(),",
        "    account: " + JSON.stringify(plan.account) + ",",
        "    command: redactTerminalCommand(entry.command),",
        "    screen: { width: entry.screen.width, height: entry.screen.height, lines: entry.screen.lines, events: entry.screen.events.length },",
        "    transcript: includeTranscript ? entry.transcript : undefined,",
        "    transcriptRedacted: !includeTranscript,",
        "  }",
        "  await appendFile(join(process.cwd(), \"terminal-journal.jsonl\"), `${JSON.stringify(payload)}\\n`)",
        "}",
        "",
        "function isTerminalMutation(command: string): boolean {",
        "  return /(^|\\n)\\s*(ED|COPY|DELETE|CLEAR-FILE|CREATE-FILE|RESIZE|UPDATE|WRITE|MATWRITE|FILEDELETE|CATALOG|COMPILE|BASIC|RUNOFF|T-DELETE)\\b/i.test(command)",
        "}",
        "",
        "async function assertTerminalAccess(req: any, command: string): Promise<void> {",
        "  if (process.env.D3CODE_MOCK === \"1\") return",
        "  if (process.env.D3CODE_TERMINAL_ENABLED !== \"1\") {",
        "    throw new Error(\"D3 terminal send blocked. Set D3CODE_TERMINAL_ENABLED=1 only after profile-doctor and terminal-capture live proof are complete.\")",
        "  }",
        "  if (isTerminalMutation(command)) await assertMutationAccess(req, \"terminal\")",
        "}",
        "",
        "function blankScreen(width: number, height: number): string[] {",
        "  return Array.from({ length: height }, () => \" \".repeat(width))",
        "}",
        "",
        "function parseTerminalScreen(transcript: string, width = 80, height = 24) {",
        "  const lines = blankScreen(width, height)",
        "  const events: Array<{ type: string; x?: number; y?: number; text?: string }> = []",
        "  let x = 0",
        "  let y = 0",
        "  function put(text: string) {",
        "    if (!text) return",
        "    events.push({ type: \"text\", x, y, text })",
        "    for (const char of text) {",
        "      if (char === \"\\n\") { x = 0; y = Math.min(height - 1, y + 1); continue }",
        "      if (char === \"\\r\") { x = 0; continue }",
        "      if (x >= width) { x = 0; y = Math.min(height - 1, y + 1) }",
        "      const row = lines[y] ?? \" \".repeat(width)",
        "      lines[y] = row.slice(0, x) + char + row.slice(x + 1)",
        "      x += 1",
        "    }",
        "  }",
        "  const tokens = transcript.split(/(@\\(-?\\d+\\)|@\\(\\d+,\\d+\\)|\\u001b\\[[0-9;]*[A-Za-z])/g).filter(Boolean)",
        "  for (const token of tokens) {",
        "    if (/^@\\(-1\\)$/.test(token) || /^\\u001b\\[[0-9;]*[HJ]$/.test(token)) {",
        "      lines.splice(0, lines.length, ...blankScreen(width, height)); x = 0; y = 0; events.push({ type: \"clear\" }); continue",
        "    }",
        "    const cursor = token.match(/^@\\((\\d+),(\\d+)\\)$/)",
        "    if (cursor) { x = Math.max(0, Math.min(width - 1, Number(cursor[1]))); y = Math.max(0, Math.min(height - 1, Number(cursor[2]))); events.push({ type: \"cursor\", x, y }); continue }",
        "    put(token)",
        "  }",
        "  return { width, height, lines, events }",
        "}",
        "",
        "async function handleTerminalSend(req: any) {",
        "  const body = await readBody(req) as { command?: string; width?: number; height?: number }",
        "  const command = String(body.command ?? \"\").trim()",
        "  if (!command) throw new Error(\"D3 terminal command is required.\")",
        "  await assertTerminalAccess(req, command)",
        "  const transcript = await d3.tcl(command)",
        "  const screen = parseTerminalScreen(transcript, Number(body.width ?? 80), Number(body.height ?? 24))",
        "  await writeTerminalJournal({ command, transcript, screen })",
        "  return { command, transcript, screen, events: screen.events.length }",
        "}",
        "",
        "const server = createServer(async (req, res) => {",
        "  try {",
        "    const url = new URL(req.url ?? \"/\", \"http://localhost\")",
        "    if (req.method === \"GET\" && [\"/\", \"/app.js\", \"/styles.css\", \"/ui-plan.json\", \"/ide-data.json\", \"/proof-data.json\", \"/skill-manifest.json\", \"/reference-skill-audit.json\", \"/subagent-prompts.json\", \"/live-operator-runbook.json\", \"/ide-terminal.json\", \"/data-validation-plan.json\", \"/index-validation-plan.json\", \"/code-modernization-plan.json\", \"/screen-modernization-plan.json\"].includes(url.pathname)) return sendStatic(res, url.pathname)",
        "    if (req.method === \"GET\" && url.pathname === \"/health\") return send(res, 200, { ok: true, account: " + JSON.stringify(plan.account) + " })",
        "    if (req.method === \"GET\" && url.pathname === \"/openapi.json\") return send(res, 200, JSON.parse(await readFile(join(process.cwd(), \"openapi.json\"), \"utf8\")))",
        "    if (req.method === \"GET\" && url.pathname === \"/access-plan.json\") return send(res, 200, await loadAccessPlan())",
        "    if (req.method === \"GET\" && url.pathname === \"/connector-strategy.json\") return send(res, 200, JSON.parse(await readFile(join(process.cwd(), \"d3-connector-strategy.json\"), \"utf8\")))",
        "    if (req.method === \"POST\" && url.pathname === \"/terminal/send\") return send(res, 200, await handleTerminalSend(req))",
        "    for (const [resource, handlers] of Object.entries(routes)) {",
        "      if (url.pathname === `/${resource}` && req.method === \"GET\") return send(res, 200, await handlers.list())",
        "      if (url.pathname === `/${resource}` && req.method === \"POST\") {",
        "        await assertMutationAccess(req, resource)",
        "        const body = await readBody(req)",
        "        const created = await handlers.create(body)",
        "        await writeMutationJournal({ action: \"create\", resource, id: (created as any)?.id ?? (body as any)?.id, after: created })",
        "        return send(res, 201, created)",
        "      }",
        "      const detail = url.pathname.match(new RegExp(`^/${resource}/([^/]+)$`))",
        "      if (detail && req.method === \"GET\") {",
        "        const found = await handlers.get(decodeURIComponent(detail[1]!))",
        "        return found ? send(res, 200, found) : send(res, 404, { error: \"not found\" })",
        "      }",
        "      if (detail && req.method === \"PATCH\") {",
        "        await assertMutationAccess(req, resource)",
        "        const id = decodeURIComponent(detail[1]!)",
        "        const before = await handlers.get(id)",
        "        const updated = await handlers.update(id, await readBody(req))",
        "        await writeMutationJournal({ action: \"update\", resource, id, before, after: updated })",
        "        return send(res, 200, updated)",
        "      }",
        "    }",
        "    return send(res, 404, { error: \"not found\" })",
        "  } catch (error) {",
        "    return send(res, 500, { error: error instanceof Error ? error.message : String(error) })",
        "  }",
        "})",
        "",
        "const port = Number(process.env.PORT ?? 3000)",
        "server.listen(port, () => {",
        "  console.log(`D3 migration API listening on http://localhost:${port}`)",
        "})",
        "",
      ].join("\n"),
    },
    {
      path: "public/index.html",
      content: [
        "<!doctype html>",
        "<html lang=\"en\">",
        "<head>",
        "  <meta charset=\"utf-8\">",
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
        `  <title>${plan.account} D3 Migration</title>`,
        "  <link rel=\"stylesheet\" href=\"/styles.css\">",
        "</head>",
        "<body>",
        "  <main class=\"shell\">",
        "    <section class=\"toolbar\">",
        `      <h1>${plan.account} D3 Migration</h1>`,
        "      <div id=\"health\" class=\"status\">Checking API...</div>",
        "    </section>",
        "    <section class=\"layout\">",
        "      <nav id=\"resources\" class=\"resources\"></nav>",
        "      <section class=\"panel\">",
        "        <header>",
        "          <h2 id=\"resource-title\">Resource</h2>",
        "          <button id=\"refresh\" type=\"button\">Refresh</button>",
        "        </header>",
        "        <div id=\"screen\" class=\"screen-plan\"></div>",
        "        <pre id=\"output\" class=\"output\">Select a resource.</pre>",
        "      </section>",
        "      <section class=\"panel ide-panel\">",
        "        <header>",
        "          <h2>D3 IDE</h2>",
        "          <span id=\"ide-summary\" class=\"status\">Loading estate...</span>",
        "        </header>",
        "        <div id=\"IDE\" class=\"IDE\">No IDE evidence bundled yet.</div>",
        "      </section>",
      "      <section class=\"panel proof-panel\">",
        "        <header>",
        "          <h2>Proof</h2>",
        "          <span id=\"proof-summary\" class=\"status\">Loading proof...</span>",
        "        </header>",
      "        <div id=\"proof\" class=\"proof\">No proof IDE bundled yet.</div>",
      "      </section>",
      "      <section class=\"panel validation-panel\">",
      "        <header>",
      "          <h2>D3 Validation</h2>",
      "          <span id=\"validation-summary\" class=\"status\">Loading validation...</span>",
      "        </header>",
      "        <div id=\"validation\" class=\"validation\">No data/index validation plans bundled yet.</div>",
      "      </section>",
      "      <section class=\"panel modernization-panel\">",
      "        <header>",
      "          <h2>D3 Modernization</h2>",
      "          <span id=\"modernization-summary\" class=\"status\">Loading modernization...</span>",
      "        </header>",
      "        <div id=\"modernization\" class=\"modernization\">No code/screen modernization plans bundled yet.</div>",
      "      </section>",
      "      <section class=\"panel skill-panel\">",
        "        <header>",
        "          <h2>Baked Skills</h2>",
        "          <span id=\"skill-summary\" class=\"status\">Loading skills...</span>",
        "        </header>",
        "        <div id=\"skill-manifest\" class=\"skill-manifest\">No skill manifest bundled yet.</div>",
        "      </section>",
        "      <section class=\"panel operations-panel\">",
        "        <header>",
        "          <h2>D3 Operations</h2>",
        "          <span id=\"operations-summary\" class=\"status\">Loading operations...</span>",
        "        </header>",
        "        <div id=\"operations\" class=\"operations\">No subagent or live runbook evidence bundled yet.</div>",
        "      </section>",
        "      <section class=\"panel terminal-panel\">",
        "        <header>",
        "          <h2>D3 Terminal</h2>",
        "          <span id=\"terminal-summary\" class=\"status\">Loading terminal contract...</span>",
        "        </header>",
        "        <div id=\"terminal-contract\" class=\"terminal-contract\">No IDE terminal contract bundled yet.</div>",
        "        <input id=\"terminal-command\" class=\"terminal-command\" value=\"SELECT " + (plan.resources[0]?.file ?? "MD") + "\" aria-label=\"D3 terminal command\">",
        "        <button id=\"terminal-send\" type=\"button\">Send</button>",
        "        <pre id=\"terminal-output\" class=\"output terminal-output\">Terminal transcript and parsed screen buffer appear here.</pre>",
        "      </section>",
        "      <section class=\"panel connector-panel\">",
        "        <header>",
        "          <h2>D3 Connector</h2>",
        "          <span id=\"connector-summary\" class=\"status\">Loading connector...</span>",
        "        </header>",
        "        <div id=\"connector\" class=\"connector\">No connector strategy bundled yet.</div>",
        "      </section>",
        "    </section>",
        "  </main>",
        "  <script type=\"module\" src=\"/app.js\"></script>",
        "</body>",
        "</html>",
        "",
      ].join("\n"),
    },
    {
      path: "public/ide-terminal.json",
      content: `${JSON.stringify(ideTerminalContract, null, 2)}\n`,
    },
    {
      path: "public/data-validation-plan.json",
      content: `${JSON.stringify(generatedDataValidationPlan, null, 2)}\n`,
    },
    {
      path: "public/index-validation-plan.json",
      content: `${JSON.stringify(generatedIndexValidationPlan, null, 2)}\n`,
    },
    {
      path: "public/code-modernization-plan.json",
      content: `${JSON.stringify(generatedCodeModernizationPlan, null, 2)}\n`,
    },
    {
      path: "public/screen-modernization-plan.json",
      content: `${JSON.stringify(generatedScreenModernizationPlan, null, 2)}\n`,
    },
    {
      path: "public/subagent-prompts.json",
      content: `${JSON.stringify(generatedSubagentPrompts, null, 2)}\n`,
    },
    {
      path: "public/live-operator-runbook.json",
      content: `${JSON.stringify(generatedLiveRunbook, null, 2)}\n`,
    },
    {
      path: "public/reference-skill-audit.json",
      content: `${JSON.stringify(generatedReferenceSkillAudit, null, 2)}\n`,
    },
    {
      path: "public/app.js",
      content: [
        `const resources = ${resourceManifest(plan)};`,
        "let uiPlan;",
        "let selected = resources[0]?.resource;",
        "const resourceNav = document.querySelector(\"#resources\");",
        "const title = document.querySelector(\"#resource-title\");",
        "const output = document.querySelector(\"#output\");",
        "const screen = document.querySelector(\"#screen\");",
        "const health = document.querySelector(\"#health\");",
        "const refresh = document.querySelector(\"#refresh\");",
        "const IDE = document.querySelector(\"#IDE\");",
        "const ideSummary = document.querySelector(\"#ide-summary\");",
        "const proof = document.querySelector(\"#proof\");",
        "const proofSummary = document.querySelector(\"#proof-summary\");",
        "const validation = document.querySelector(\"#validation\");",
        "const validationSummary = document.querySelector(\"#validation-summary\");",
        "const modernization = document.querySelector(\"#modernization\");",
        "const modernizationSummary = document.querySelector(\"#modernization-summary\");",
        "const skillManifest = document.querySelector(\"#skill-manifest\");",
        "const skillSummary = document.querySelector(\"#skill-summary\");",
        "const operations = document.querySelector(\"#operations\");",
        "const operationsSummary = document.querySelector(\"#operations-summary\");",
        "const terminalContract = document.querySelector(\"#terminal-contract\");",
        "const terminalSummary = document.querySelector(\"#terminal-summary\");",
        "const terminalInput = document.querySelector(\"#terminal-command\");",
        "const terminalSend = document.querySelector(\"#terminal-send\");",
        "const terminalOutput = document.querySelector(\"#terminal-output\");",
        "const connector = document.querySelector(\"#connector\");",
        "const connectorSummary = document.querySelector(\"#connector-summary\");",
        "",
        "function renderResources() {",
        "  resourceNav.innerHTML = \"\";",
        "  for (const item of resources) {",
        "    const button = document.createElement(\"button\");",
        "    button.type = \"button\";",
        "    button.textContent = `${item.resource} (${item.file})`;",
        "    button.className = item.resource === selected ? \"active\" : \"\";",
        "    button.addEventListener(\"click\", () => { selected = item.resource; renderResources(); loadResource(); });",
        "    resourceNav.append(button);",
        "  }",
        "}",
        "",
        "function renderScreenPlan() {",
        "  const spec = uiPlan?.screens?.find((item) => item.resource === selected);",
        "  if (!screen || !spec) { if (screen) screen.innerHTML = \"\"; return; }",
        "  const fields = spec.fields.map((field) => `<span>${field.name}<small>${field.kind}</small></span>`).join(\"\");",
        "  const actions = spec.actions.map((action) => `<span>${action}</span>`).join(\"\");",
        "  const warnings = spec.warnings.length ? `<ul>${spec.warnings.map((warning) => `<li>${warning}</li>`).join(\"\")}</ul>` : \"<p>No known screen warnings.</p>\";",
        "  screen.innerHTML = `<h3>${spec.title}</h3><p>${spec.layout} from D3 file ${spec.d3File}</p><div class=\"chips\">${fields}</div><h4>Actions</h4><div class=\"chips actions\">${actions}</div><h4>Warnings</h4>${warnings}`;",
        "}",
        "",
        "async function loadHealth() {",
        "  const response = await fetch(\"/health\");",
        "  const data = await response.json();",
        "  health.textContent = data.ok ? `API ready for ${data.account}` : \"API unavailable\";",
        "}",
        "",
        "async function loadResource() {",
        "  if (!selected) return;",
        "  title.textContent = selected;",
        "  renderScreenPlan();",
        "  output.textContent = \"Loading...\";",
        "  const response = await fetch(`/${selected}`);",
        "  const data = await response.json();",
        "  output.textContent = JSON.stringify(data, null, 2);",
        "}",
        "",
        "async function loadUiPlan() {",
        "  try {",
        "    const response = await fetch(\"/ui-plan.json\");",
        "    if (response.ok) uiPlan = await response.json();",
        "  } catch {}",
        "}",
        "",
        "function renderIdeEstate(data) {",
        "  if (!IDE || !data) return;",
        "  const panel = (id) => data.panels?.find((item) => item.id === id)?.items ?? [];",
        "  const nodesByKind = (kind) => data.nodes?.filter((node) => node.kind === kind) ?? [];",
        "  const list = (items) => items.length ? `<ul>${items.map((item) => `<li>${item}</li>`).join(\"\")}</ul>` : \"<p>none</p>\";",
        "  const nodeList = (kind) => nodesByKind(kind).map((node) => `<span class=\"ide-node ${node.risk}\">${node.label}</span>`).join(\"\") || \"<span class=\\\"muted\\\">none</span>\";",
        "  IDE.innerHTML = `<div class=\"ide-grid\"><section><h3>Estate</h3>${list(panel(\"estate\"))}</section><section><h3>Integrity Risks</h3>${list(panel(\"risks\"))}</section><section><h3>Access</h3>${list(panel(\"access\"))}</section><section><h3>D3 Logical Model</h3>${list(panel(\"model\"))}</section></div><h3>Graph Nodes</h3><div class=\"ide-nodes\"><strong>Files</strong>${nodeList(\"file\")}<strong>Indexes</strong>${nodeList(\"index\")}<strong>Programs</strong>${nodeList(\"program\")}<strong>Screens</strong>${nodeList(\"screen\")}</div>`;",
        "  if (ideSummary) ideSummary.textContent = `${data.nodes?.length ?? 0} nodes / ${data.edges?.length ?? 0} edges`;",
        "}",
        "",
        "async function loadIdeEstate() {",
        "  try {",
        "    const response = await fetch(\"/ide-data.json\");",
        "    if (response.ok) renderIdeEstate(await response.json());",
        "  } catch {",
        "    if (ideSummary) ideSummary.textContent = \"No IDE data\";",
        "  }",
        "}",
        "",
        "function renderProofData(data) {",
        "  if (!proof || !data) return;",
        "  const gates = data.readiness?.gates ?? [];",
        "  const requirements = data.completion?.requirements ?? [];",
        "  const chips = (items) => items.slice(0, 12).map((item) => `<span class=\"proof-chip ${item.status}\">${item.id}: ${item.status}</span>`).join(\"\") || \"<span class=\\\"muted\\\">none</span>\";",
        "  const blockers = (data.release?.blockers ?? []).slice(0, 8).map((item) => `<li>${item}</li>`).join(\"\") || \"<li>none</li>\";",
        "  proof.innerHTML = `<div class=\"proof-grid\"><section><h3>Readiness</h3><p>${data.readiness?.ready ? \"ready\" : \"not ready\"}</p>${chips(gates)}</section><section><h3>Completion</h3><p>${data.completion?.complete ? \"complete\" : \"incomplete\"}</p>${chips(requirements)}</section><section><h3>Release</h3><p>${data.release?.decision ?? \"unknown\"}</p><ul>${blockers}</ul></section><section><h3>QA</h3><p>${data.qaEvidence?.ready ? \"ready\" : \"missing\"}</p><p>${data.qaEvidence?.source ?? \"no recorded QA evidence\"}</p></section></div>`;",
        "  if (proofSummary) proofSummary.textContent = `${data.release?.decision ?? \"unknown\"} / ${data.readiness?.ready ? \"ready\" : \"not ready\"}`;",
        "}",
        "",
        "async function loadProofData() {",
        "  try {",
        "    const response = await fetch(\"/proof-data.json\");",
        "    if (response.ok) renderProofData(await response.json());",
        "  } catch {",
        "    if (proofSummary) proofSummary.textContent = \"No proof data\";",
        "  }",
        "}",
        "",
        "function renderValidationPlans(dataPlan, indexPlan) {",
        "  if (!validation) return;",
        "  const dataItems = dataPlan?.items ?? [];",
        "  const indexItems = indexPlan?.items ?? [];",
        "  const rows = (items, kind) => items.slice(0, 10).map((item) => `<li><strong>${kind}</strong> ${item.file}: ${item.subject ?? item.index} (${item.status})</li>`).join(\"\") || \"<li>none</li>\";",
        "  validation.innerHTML = `<div class=\"validation-grid\"><section><h3>Data Shape</h3><ul>${rows(dataItems, \"data\")}</ul></section><section><h3>Indexes</h3><ul>${rows(indexItems, \"index\")}</ul></section></div>`;",
        "  if (validationSummary) validationSummary.textContent = `${dataItems.length} data / ${indexItems.length} index items`;",
        "}",
        "",
        "async function loadValidationPlans() {",
        "  try {",
        "    const [dataResponse, indexResponse] = await Promise.all([fetch(\"/data-validation-plan.json\"), fetch(\"/index-validation-plan.json\")]);",
        "    if (dataResponse.ok && indexResponse.ok) renderValidationPlans(await dataResponse.json(), await indexResponse.json());",
        "    else if (validationSummary) validationSummary.textContent = \"No validation data\";",
        "  } catch {",
        "    if (validationSummary) validationSummary.textContent = \"No validation data\";",
        "  }",
        "}",
        "",
        "function renderModernizationPlans(codePlan, screenPlan) {",
        "  if (!modernization) return;",
        "  const codeItems = codePlan?.items ?? [];",
        "  const screenItems = screenPlan?.items ?? [];",
        "  const rows = (items, kind) => items.slice(0, 10).map((item) => `<li><strong>${kind}</strong> ${item.program}: ${item.subject ?? item.risk} (${item.priority})</li>`).join(\"\") || \"<li>none</li>\";",
        "  modernization.innerHTML = `<div class=\"modernization-grid\"><section><h3>BASIC Code</h3><ul>${rows(codeItems, \"code\")}</ul></section><section><h3>Legacy Screens</h3><ul>${rows(screenItems, \"screen\")}</ul></section></div>`;",
        "  if (modernizationSummary) modernizationSummary.textContent = `${codeItems.length} code / ${screenItems.length} screen items`;",
        "}",
        "",
        "async function loadModernizationPlans() {",
        "  try {",
        "    const [codeResponse, screenResponse] = await Promise.all([fetch(\"/code-modernization-plan.json\"), fetch(\"/screen-modernization-plan.json\")]);",
        "    if (codeResponse.ok && screenResponse.ok) renderModernizationPlans(await codeResponse.json(), await screenResponse.json());",
        "    else if (modernizationSummary) modernizationSummary.textContent = \"No modernization data\";",
        "  } catch {",
        "    if (modernizationSummary) modernizationSummary.textContent = \"No modernization data\";",
        "  }",
        "}",
        "",
        "function renderSkillManifest(data, audit) {",
        "  if (!skillManifest || !data) return;",
        "  const modes = data.skillPack?.modes ?? [];",
        "  const phases = data.phaseSkillMap ?? [];",
        "  const coverage = data.coverage?.items ?? [];",
        "  const references = data.referenceSkills?.families ?? [];",
        "  const auditItems = audit?.items ?? [];",
        "  const auditCounts = auditItems.reduce((acc, item) => { acc[item.status] = (acc[item.status] ?? 0) + 1; return acc; }, {});",
        "  const modeList = modes.map((mode) => `<section><h3>${mode.mode}</h3><p>${mode.title}</p><p>safety=${mode.safety}</p><div class=\"chips\">${(mode.skills ?? []).slice(0, 8).map((skill) => `<span>${skill.id}<small>${skill.source}</small></span>`).join(\"\")}</div></section>`).join(\"\");",
        "  const phaseList = phases.map((phase) => `<section><h3>${phase.phase}</h3><p>${phase.mode} / ${phase.status}</p><div class=\"chips\">${(phase.skills ?? []).slice(0, 6).map((skill) => `<span>${skill}</span>`).join(\"\")}</div><p>${(phase.subagents ?? []).join(\", \") || \"no subagents\"}</p></section>`).join(\"\");",
        "  const coverageList = coverage.slice(0, 8).map((item) => `<li>${item.source}: ${item.covered ? \"covered\" : \"missing\"} - ${item.expected}</li>`).join(\"\") || \"<li>none</li>\";",
        "  const auditList = auditItems.slice(0, 10).map((item) => `<li>[${item.status}] ${item.path}</li>`).join(\"\") || \"<li>none</li>\";",
        "  const outOfScope = references.filter((item) => item.status === \"out-of-scope\").map((item) => `<li>${item.source}: ${item.reference}</li>`).join(\"\") || \"<li>none</li>\";",
        "  skillManifest.innerHTML = `<h3>Modes</h3><div class=\"skill-grid\">${modeList}</div><h3>Phase Skill Map</h3><div class=\"skill-grid\">${phaseList}</div><h3>Coverage</h3><p>${data.coverage?.ready ? \"ready\" : \"not ready\"} / ${data.bakedSkills?.length ?? 0} baked skills</p><ul>${coverageList}</ul><h3>Reference Skill Audit</h3><p>${audit?.ready ? \"ready\" : \"not ready\"} / ${audit?.total ?? auditItems.length} SKILL.md mapped; baked=${auditCounts.baked ?? 0}, adapted=${auditCounts.adapted ?? 0}, out-of-scope=${auditCounts[\"out-of-scope\"] ?? 0}, unmapped=${auditCounts.unmapped ?? 0}</p><ul>${auditList}</ul><h3>Explicitly Out Of Scope</h3><ul>${outOfScope}</ul>`;",
        "  if (skillSummary) skillSummary.textContent = `${data.bakedSkills?.length ?? 0} skills / ${audit?.total ?? data.referenceSkills?.families?.length ?? 0} reference files`;",
        "}",
        "",
        "async function loadSkillManifest() {",
        "  try {",
        "    const [response, auditResponse] = await Promise.all([fetch(\"/skill-manifest.json\"), fetch(\"/reference-skill-audit.json\")]);",
        "    if (response.ok) renderSkillManifest(await response.json(), auditResponse.ok ? await auditResponse.json() : undefined);",
        "    else if (skillSummary) skillSummary.textContent = \"No skill manifest\";",
        "  } catch {",
        "    if (skillSummary) skillSummary.textContent = \"No skill manifest\";",
        "  }",
        "}",
        "",
        "function renderOperations(subagents, runbook) {",
        "  if (!operations) return;",
        "  const packets = subagents?.packets ?? [];",
        "  const phases = runbook?.phases ?? [];",
        "  const packetList = packets.map((packet) => `<section><h3>${packet.agent}</h3><p>${packet.title}</p><p>safety=${packet.safety}</p><div class=\"chips\">${(packet.allowedTools ?? []).slice(0, 6).map((tool) => `<span>${tool}</span>`).join(\"\")}</div><h4>Denied</h4><ul>${(packet.deniedActions ?? []).slice(0, 4).map((action) => `<li>${action}</li>`).join(\"\")}</ul></section>`).join(\"\") || \"<section><h3>Subagents</h3><p>none</p></section>\";",
        "  const phaseList = phases.map((phase) => `<section><h3>${phase.id}</h3><p>${phase.title}</p><h4>Commands</h4><ul>${(phase.commands ?? []).slice(0, 4).map((command) => `<li>${command}</li>`).join(\"\")}</ul><h4>Evidence</h4><ul>${(phase.evidence ?? []).slice(0, 4).map((proof) => `<li>${proof}</li>`).join(\"\")}</ul></section>`).join(\"\") || \"<section><h3>Live Runbook</h3><p>none</p></section>\";",
        "  operations.innerHTML = `<h3>Subagent Boundaries</h3><div class=\"operations-grid\">${packetList}</div><h3>Live Operator Runbook</h3><div class=\"operations-grid\">${phaseList}</div>`;",
        "  if (operationsSummary) operationsSummary.textContent = `${packets.length} packets / ${phases.length} live phases`;",
        "}",
        "",
        "async function loadOperations() {",
        "  try {",
        "    const [subagentsResponse, runbookResponse] = await Promise.all([fetch(\"/subagent-prompts.json\"), fetch(\"/live-operator-runbook.json\")]);",
        "    if (subagentsResponse.ok && runbookResponse.ok) renderOperations(await subagentsResponse.json(), await runbookResponse.json());",
        "    else if (operationsSummary) operationsSummary.textContent = \"No operations data\";",
        "  } catch {",
        "    if (operationsSummary) operationsSummary.textContent = \"No operations data\";",
        "  }",
        "}",
        "",
        "function renderConnectorStrategy(data) {",
        "  if (!connector || !data) return;",
        "  const layers = data.layers ?? [];",
        "  const layerList = layers.map((layer) => `<section><h3>${layer.id}</h3><p class=\"connector-status ${layer.status}\">${layer.status}</p><p>${layer.purpose}</p><h4>Proof</h4><ul>${(layer.proof ?? []).map((item) => `<li>${item}</li>`).join(\"\")}</ul></section>`).join(\"\");",
        "  const requirements = (data.ideRequirements ?? []).map((item) => `<li>${item}</li>`).join(\"\") || \"<li>none</li>\";",
        "  connector.innerHTML = `<p>${data.answer ?? \"No connector answer bundled.\"}</p><div class=\"connector-grid\">${layerList}</div><h3>IDE Requirements</h3><ul>${requirements}</ul>`;",
        "  if (connectorSummary) connectorSummary.textContent = `${layers.length} layers / ${data.account ?? \"unknown\"}`;",
        "}",
        "",
        "async function loadConnectorStrategy() {",
        "  try {",
        "    const response = await fetch(\"/connector-strategy.json\");",
        "    if (response.ok) renderConnectorStrategy(await response.json());",
        "    else if (connectorSummary) connectorSummary.textContent = \"No connector data\";",
        "  } catch {",
        "    if (connectorSummary) connectorSummary.textContent = \"No connector data\";",
        "  }",
        "}",
        "",
        "function renderTerminalContract(data) {",
        "  if (!terminalContract || !data) return;",
        "  const features = data.features ?? [];",
        "  const featureList = features.map((feature) => `<section><h3>${feature.title ?? feature.id}</h3><p>${feature.status}</p><p>${feature.detail ?? \"\"}</p><ul>${(feature.proof ?? []).slice(0, 4).map((item) => `<li>${item}</li>`).join(\"\")}</ul></section>`).join(\"\");",
        "  const policy = data.sendPolicy;",
        "  const blocked = (policy?.blockedUntil ?? []).map((item) => `<li>${item}</li>`).join(\"\") || \"<li>none</li>\";",
        "  const commands = (data.commandPlan ?? []).map((item) => `<section><h3>${item.title}</h3><p>${item.safety}</p><code>${item.example}</code><ul>${(item.requiredProof ?? []).map((proof) => `<li>${proof}</li>`).join(\"\")}</ul></section>`).join(\"\") || \"<section><h3>No command plan</h3><p>none</p></section>\";",
        "  const parityEvidence = (data.screenParity?.requiredEvidence ?? []).map((item) => `<li>${item}</li>`).join(\"\") || \"<li>none</li>\";",
        "  const unsupported = (data.screenParity?.unsupportedUntilProven ?? []).map((item) => `<li>${item}</li>`).join(\"\") || \"<li>none</li>\";",
        "  const liveProof = (data.requiredLiveProof ?? []).map((item) => `<li>${item}</li>`).join(\"\") || \"<li>none</li>\";",
        "  terminalContract.innerHTML = `<p>${data.terminalModel ?? \"unknown terminal model\"}</p><div class=\"terminal-policy\"><strong>Terminal sends</strong><span>${policy?.enabledByDefault ? \"enabled\" : \"blocked by default\"}</span><span>${policy?.enableEnv ?? \"D3CODE_TERMINAL_ENABLED=1\"}</span><span>${policy?.mutationEnv ?? \"D3CODE_ALLOW_WRITES=1\"}</span></div><h3>Blocked Until</h3><ul>${blocked}</ul><h3>Command Plan</h3><div class=\"terminal-contract-grid\">${commands}</div><h3>Features</h3><div class=\"terminal-contract-grid\">${featureList}</div><h3>PowerTerm Screen Parity</h3><p>${data.screenParity?.model ?? \"raw transcript plus screen buffer\"}</p><ul>${parityEvidence}${unsupported}</ul><h3>Live Proof Required</h3><ul>${liveProof}</ul>`;",
        "  if (terminalSummary) terminalSummary.textContent = `${data.attachMode ?? \"unknown\"} / ${data.terminalModel ?? \"unknown\"}`;",
        "}",
        "",
        "async function loadTerminalContract() {",
        "  try {",
        "    const response = await fetch(\"/ide-terminal.json\");",
        "    if (response.ok) renderTerminalContract(await response.json());",
        "    else if (terminalSummary) terminalSummary.textContent = \"No terminal contract\";",
        "  } catch {",
        "    if (terminalSummary) terminalSummary.textContent = \"No terminal contract\";",
        "  }",
        "}",
        "",
        "async function sendTerminalCommand() {",
        "  if (!terminalInput || !terminalOutput) return;",
        "  const command = terminalInput.value.trim();",
        "  if (!command) return;",
        "  terminalOutput.textContent = \"Sending...\";",
        "  const response = await fetch(\"/terminal/send\", {",
        "    method: \"POST\",",
        "    headers: { \"content-type\": \"application/json\" },",
        "    body: JSON.stringify({ command, width: 80, height: 12 }),",
        "  });",
        "  const data = await response.json();",
        "  terminalOutput.textContent = response.ok ? data.screen.lines.join(\"\\n\") : data.error;",
        "}",
        "",
        "refresh.addEventListener(\"click\", loadResource);",
        "terminalSend?.addEventListener(\"click\", () => { sendTerminalCommand().catch((error) => { terminalOutput.textContent = error.message; }); });",
        "await loadUiPlan();",
        "await loadIdeEstate();",
        "await loadProofData();",
        "await loadValidationPlans();",
        "await loadModernizationPlans();",
        "await loadSkillManifest();",
        "await loadOperations();",
        "await loadConnectorStrategy();",
        "await loadTerminalContract();",
        "renderResources();",
        "loadHealth().catch((error) => { health.textContent = error.message; });",
        "loadResource().catch((error) => { output.textContent = error.message; });",
        "",
      ].join("\n"),
    },
    {
      path: "public/styles.css",
      content: [
        ":root { color-scheme: light; font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif; }",
        "body { margin: 0; background: #f6f7f9; color: #111827; }",
        ".shell { max-width: 1180px; margin: 0 auto; padding: 24px; }",
        ".toolbar { display: flex; align-items: center; justify-content: space-between; gap: 16px; margin-bottom: 18px; }",
        "h1, h2 { margin: 0; font-weight: 700; letter-spacing: 0; }",
        ".status { border: 1px solid #cbd5e1; background: #ffffff; padding: 8px 10px; font-size: 14px; }",
        ".layout { display: grid; grid-template-columns: minmax(180px, 260px) 1fr; gap: 16px; }",
        ".resources { display: flex; flex-direction: column; gap: 8px; }",
        "button { border: 1px solid #9ca3af; background: #ffffff; color: #111827; padding: 8px 10px; text-align: left; cursor: pointer; }",
        "button.active, button:hover { border-color: #2563eb; background: #eff6ff; }",
        ".panel { background: #ffffff; border: 1px solid #cbd5e1; padding: 16px; }",
        ".panel header { display: flex; align-items: center; justify-content: space-between; gap: 12px; margin-bottom: 12px; }",
        ".screen-plan { border: 1px solid #cbd5e1; background: #f8fafc; padding: 12px; margin-bottom: 12px; }",
        ".screen-plan h3, .screen-plan h4, .screen-plan p { margin: 0 0 8px; }",
        ".chips { display: flex; flex-wrap: wrap; gap: 6px; margin-bottom: 10px; }",
        ".chips span { border: 1px solid #cbd5e1; background: #ffffff; padding: 5px 7px; font-size: 13px; }",
        ".chips small { display: block; color: #64748b; }",
        ".output { min-height: 360px; overflow: auto; background: #111827; color: #e5e7eb; padding: 14px; font-size: 13px; line-height: 1.5; }",
        ".ide-panel { grid-column: 2; }",
        ".IDE { font-size: 13px; }",
        ".proof-panel { grid-column: 2; }",
        ".proof { font-size: 13px; }",
        ".validation-panel { grid-column: 2; }",
        ".validation { font-size: 13px; }",
        ".modernization-panel { grid-column: 2; }",
        ".modernization { font-size: 13px; }",
        ".skill-panel { grid-column: 2; }",
        ".skill-manifest { font-size: 13px; }",
        ".operations-panel { grid-column: 2; }",
        ".operations { font-size: 13px; }",
        ".ide-grid, .proof-grid, .validation-grid, .modernization-grid, .skill-grid, .operations-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; margin-bottom: 12px; }",
        ".ide-grid section, .proof-grid section, .validation-grid section, .modernization-grid section, .skill-grid section, .operations-grid section { border: 1px solid #cbd5e1; background: #f8fafc; padding: 10px; }",
        ".ide-grid h3, .ide-nodes h3 { margin: 0 0 8px; }",
        ".ide-node { display: inline-block; border: 1px solid #9ca3af; padding: 4px 6px; margin: 3px; }",
        ".ide-node.ok { border-color: #15803d; } .ide-node.review { border-color: #a16207; } .ide-node.warning { border-color: #c2410c; } .ide-node.blocked { border-color: #b91c1c; }",
        ".ide-nodes strong { display: block; margin-top: 8px; }",
        ".proof-chip { display: inline-block; border: 1px solid #9ca3af; padding: 4px 6px; margin: 3px; }",
        ".proof-chip.ok, .proof-chip.proven { border-color: #15803d; } .proof-chip.warning, .proof-chip.partial { border-color: #a16207; } .proof-chip.missing { border-color: #b45309; } .proof-chip.blocker { border-color: #b91c1c; }",
        ".muted { color: #64748b; }",
        ".terminal-panel { grid-column: 2; }",
        ".connector-panel { grid-column: 2; }",
        ".terminal-contract { font-size: 13px; border: 1px solid #cbd5e1; background: #f8fafc; padding: 10px; margin-bottom: 10px; }",
        ".terminal-contract-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 10px; margin: 10px 0; }",
        ".terminal-contract-grid section { border: 1px solid #cbd5e1; background: #ffffff; padding: 10px; }",
        ".terminal-contract-grid h3, .terminal-contract-grid p { margin: 0 0 8px; }",
        ".terminal-policy { display: flex; flex-wrap: wrap; gap: 8px; align-items: center; margin: 10px 0; }",
        ".terminal-policy span, .terminal-policy strong { border: 1px solid #cbd5e1; background: #ffffff; padding: 5px 7px; }",
        ".terminal-contract code { display: block; white-space: normal; overflow-wrap: anywhere; border: 1px solid #cbd5e1; background: #ffffff; padding: 6px; margin-bottom: 8px; }",
        ".terminal-command { box-sizing: border-box; width: 100%; border: 1px solid #9ca3af; padding: 8px 10px; margin-bottom: 10px; font: inherit; }",
        ".terminal-output { min-height: 180px; white-space: pre; }",
        ".connector { font-size: 13px; }",
        ".connector-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(190px, 1fr)); gap: 10px; margin: 12px 0; }",
        ".connector-grid section { border: 1px solid #cbd5e1; background: #f8fafc; padding: 10px; }",
        ".connector-grid h3, .connector-grid h4, .connector-grid p { margin: 0 0 8px; }",
        ".connector-status { display: inline-block; border: 1px solid #9ca3af; padding: 3px 6px; }",
        ".connector-status.ready { border-color: #15803d; } .connector-status.partial, .connector-status.spike { border-color: #a16207; } .connector-status.blocked { border-color: #b91c1c; }",
        "@media (max-width: 720px) { .toolbar, .layout { display: block; } .resources { margin-bottom: 12px; } }",
        "",
      ].join("\n"),
    },
    {
      path: "test/api-smoke.test.mjs",
      content: [
        "import assert from \"node:assert/strict\";",
        "import { spawn } from \"node:child_process\";",
        "import { existsSync, readFileSync } from \"node:fs\";",
        "import { createServer as createTcpServer } from \"node:net\";",
        "import test from \"node:test\";",
        "import { formatD3Record, parseD3Ids, parseD3Record } from \"../dist/d3-record.js\";",
        "",
        "async function freePort() {",
        "  return await new Promise((resolve, reject) => {",
        "    const server = createTcpServer();",
        "    server.on(\"error\", reject);",
        "    server.listen(0, \"127.0.0.1\", () => {",
        "      const address = server.address();",
        "      const port = typeof address === \"object\" && address ? address.port : 0;",
        "      server.close(() => resolve(port));",
        "    });",
        "  });",
        "}",
        "",
        "async function waitForJson(url, attempts = 40) {",
        "  let lastError;",
        "  for (let index = 0; index < attempts; index += 1) {",
        "    try {",
        "      const response = await fetch(url);",
        "      if (response.ok) return response.json();",
        "      lastError = new Error(`HTTP ${response.status}`);",
        "    } catch (error) {",
        "      lastError = error;",
        "    }",
        "    await new Promise((resolve) => setTimeout(resolve, 100));",
        "  }",
        "  throw lastError ?? new Error(`Timed out waiting for ${url}`);",
        "}",
        "",
        `const resources = ${JSON.stringify(plan.resources.map((resource) => resource.resource), null, 2)};`,
        `const resourceFiles = ${JSON.stringify(Object.fromEntries(plan.resources.map((resource) => [resource.resource, resource.file])), null, 2)};`,
        `const fieldMaps = ${JSON.stringify(Object.fromEntries(plan.resources.map((resource) => [resource.resource, (resource.fields ?? []).filter((field) => field.attribute !== undefined).map((field) => ({ name: field.name, attribute: field.attribute, multivalue: field.multivalue }))])), null, 2)};`,
        "const mockData = existsSync(\"mock-data.json\") ? JSON.parse(readFileSync(\"mock-data.json\", \"utf8\")) : {};",
        "",
        "test(\"generated D3 record mapper round-trips dictionary attributes\", () => {",
        "  for (const [resource, fields] of Object.entries(fieldMaps)) {",
        "    if (fields.length === 0) continue;",
        "    const attributes = {};",
        "    for (const field of fields) {",
        "      attributes[field.name] = field.multivalue ? [\"one\", \"two\"] : `${resource}-${field.name}`;",
        "    }",
        "    const raw = formatD3Record(attributes, fields);",
        "    const parsed = parseD3Record(\"SMOKE\", raw, fields);",
        "    assert.equal(parsed.id, \"SMOKE\");",
        "    for (const field of fields) {",
        "      assert.deepEqual(parsed.attributes[field.name], attributes[field.name]);",
        "    }",
        "  }",
        "});",
        "",
        "test(\"generated D3 id parser handles selected-list output\", () => {",
        "  assert.deepEqual(parseD3Ids(\"SELECT CUSTOMERS\\nID\\n100\\n101 Alice\\n2 items selected\\n\"), [\"100\", \"101\"]);",
        "});",
        "",
        "test(\"generated API starts in D3 mock mode\", async () => {",
        "  const port = await freePort();",
        "  const child = spawn(process.execPath, [\"dist/server.js\"], {",
        "    env: { ...process.env, D3CODE_MOCK: \"1\", PORT: String(port) },",
        "    stdio: [\"ignore\", \"pipe\", \"pipe\"],",
        "  });",
        "  let stderr = \"\";",
        "  child.stderr.on(\"data\", (chunk) => { stderr += chunk.toString(); });",
        "  try {",
        `    const health = await waitForJson(\`http://127.0.0.1:\${port}/health\`);`,
        `    assert.deepEqual(health, { ok: true, account: ${JSON.stringify(plan.account)} });`,
        `    const openapi = await waitForJson(\`http://127.0.0.1:\${port}/openapi.json\`);`,
        "    assert.equal(openapi.openapi, \"3.1.0\");",
        `    const accessPlan = await waitForJson(\`http://127.0.0.1:\${port}/access-plan.json\`);`,
        "    assert.ok(Array.isArray(accessPlan.users));",
        "    assert.ok(Array.isArray(accessPlan.grants));",
        `    const uiPlan = await waitForJson(\`http://127.0.0.1:\${port}/ui-plan.json\`);`,
        "    assert.ok(Array.isArray(uiPlan.screens));",
        `    const ideData = await waitForJson(\`http://127.0.0.1:\${port}/ide-data.json\`);`,
        "    assert.ok(Array.isArray(ideData.nodes));",
        "    assert.ok(Array.isArray(ideData.edges));",
        `    const proofData = await waitForJson(\`http://127.0.0.1:\${port}/proof-data.json\`);`,
        "    assert.ok(Array.isArray(proofData.readiness?.gates));",
        "    assert.ok(Array.isArray(proofData.completion?.requirements));",
        `    const dataValidation = await waitForJson(\`http://127.0.0.1:\${port}/data-validation-plan.json\`);`,
        "    assert.ok(Array.isArray(dataValidation.items));",
        `    const indexValidation = await waitForJson(\`http://127.0.0.1:\${port}/index-validation-plan.json\`);`,
        "    assert.ok(Array.isArray(indexValidation.items));",
        `    const codeModernization = await waitForJson(\`http://127.0.0.1:\${port}/code-modernization-plan.json\`);`,
        "    assert.ok(Array.isArray(codeModernization.items));",
        `    const screenModernization = await waitForJson(\`http://127.0.0.1:\${port}/screen-modernization-plan.json\`);`,
        "    assert.ok(Array.isArray(screenModernization.items));",
        `    const skillManifest = await waitForJson(\`http://127.0.0.1:\${port}/skill-manifest.json\`);`,
        "    assert.equal(skillManifest.coverage?.ready, true);",
        "    assert.ok(Array.isArray(skillManifest.bakedSkills));",
        "    assert.ok(skillManifest.phaseSkillMap.some((phase) => phase.phase === \"api\"));",
        `    const referenceSkillAudit = await waitForJson(\`http://127.0.0.1:\${port}/reference-skill-audit.json\`);`,
        "    assert.equal(referenceSkillAudit.ready, true);",
        "    assert.ok(Array.isArray(referenceSkillAudit.items));",
        "    assert.ok(referenceSkillAudit.items.some((item) => item.status === \"adapted\" || item.status === \"baked\"));",
        `    const subagentPrompts = await waitForJson(\`http://127.0.0.1:\${port}/subagent-prompts.json\`);`,
        "    assert.ok(Array.isArray(subagentPrompts.packets));",
        "    assert.ok(subagentPrompts.packets.some((packet) => Array.isArray(packet.allowedTools)));",
        "    assert.ok(subagentPrompts.packets.some((packet) => /Evidence gate/.test(packet.prompt)));",
        `    const liveRunbook = await waitForJson(\`http://127.0.0.1:\${port}/live-operator-runbook.json\`);`,
        "    assert.ok(Array.isArray(liveRunbook.phases));",
        "    assert.ok(liveRunbook.phases.some((phase) => phase.id === \"live-d3-proof\"));",
        "    assert.ok(liveRunbook.phases.some((phase) => phase.commands.some((command) => /terminal-capture|live-proof-check/.test(command))));",
        `    const connectorStrategy = await waitForJson(\`http://127.0.0.1:\${port}/connector-strategy.json\`);`,
        "    assert.ok(Array.isArray(connectorStrategy.layers));",
        "    assert.ok(connectorStrategy.layers.some((layer) => layer.id === \"screen-buffer\"));",
        "    assert.ok(connectorStrategy.layers.some((layer) => layer.id === \"uopy\"));",
        `    const ideTerminal = await waitForJson(\`http://127.0.0.1:\${port}/ide-terminal.json\`);`,
        "    assert.ok(ideTerminal.terminalModel === \"powerterm-aware-buffer\" || ideTerminal.terminalModel === \"plain-transcript\");",
        "    assert.ok(ideTerminal.features.some((feature) => feature.id === \"screen-buffer\"));",
        "    assert.ok(ideTerminal.features.some((feature) => feature.id === \"uopy\"));",
        "    assert.equal(ideTerminal.sendPolicy.enabledByDefault, false);",
        "    assert.ok(ideTerminal.commandPlan.some((command) => command.id === \"screen-capture\"));",
        "    assert.ok(ideTerminal.commandPlan.some((command) => command.id === \"compile-catalog\" && command.safety === \"confirm\"));",
        "    assert.ok(ideTerminal.screenParity.requiredEvidence.some((proof) => /@\\(\\)/.test(proof)));",
        "    assert.ok(ideTerminal.requiredLiveProof.some((proof) => /terminal-capture/.test(proof)));",
        "    for (const resource of resources) assert.ok(openapi.paths[`/${resource}`]);",
        "    if (resources.length > 0) {",
        `      const terminalResponse = await fetch(\`http://127.0.0.1:\${port}/terminal/send\`, {`,
        "        method: \"POST\",",
        "        headers: { \"content-type\": \"application/json\" },",
        "        body: JSON.stringify({ command: `SELECT ${resourceFiles[resources[0]]}`, width: 40, height: 8 }),",
        "      });",
        "      assert.equal(terminalResponse.status, 200);",
        "      const terminal = await terminalResponse.json();",
        "      assert.equal(terminal.command, `SELECT ${resourceFiles[resources[0]]}`);",
        "      assert.ok(typeof terminal.transcript === \"string\");",
        "      assert.ok(Array.isArray(terminal.screen.lines));",
        "      assert.ok(Array.isArray(terminal.screen.events));",
        "      assert.equal(existsSync(\"terminal-journal.jsonl\"), true);",
        "      const terminalJournal = readFileSync(\"terminal-journal.jsonl\", \"utf8\");",
        "      assert.match(terminalJournal, /transcriptRedacted/);",
        "      assert.match(terminalJournal, /\"events\"/);",
        `      const createResponse = await fetch(\`http://127.0.0.1:\${port}/\${resources[0]}\`, {`,
        "        method: \"POST\",",
        "        headers: { \"content-type\": \"application/json\" },",
        "        body: JSON.stringify({ id: \"JOURNAL-SMOKE\", attributes: {} }),",
        "      });",
        "      assert.equal(createResponse.status, 201);",
        "      assert.equal(existsSync(\"mutation-journal.jsonl\"), true);",
        "      const journal = readFileSync(\"mutation-journal.jsonl\", \"utf8\");",
        "      assert.match(journal, /JOURNAL-SMOKE/);",
        "      assert.match(journal, /\"action\":\"create\"/);",
        "      assert.match(journal, /\"rollback\"/);",
        "    }",
        "    for (const resource of resources) {",
        `      const list = await waitForJson(\`http://127.0.0.1:\${port}/\${resource}\`);`,
        "      assert.ok(Array.isArray(list));",
        "      const records = mockData[resourceFiles[resource]] ?? mockData[String(resourceFiles[resource]).toUpperCase()] ?? [];",
        "      assert.equal(list.length, records.length);",
        "      if (records.length > 0) assert.equal(list[0].id, records[0].id);",
        "    }",
        "  } finally {",
        "    child.kill(\"SIGTERM\");",
        "  }",
        "  assert.equal(stderr, \"\");",
        "});",
        "",
        "test(\"generated API blocks D3 mutations unless writes are explicitly enabled\", async () => {",
        "  const port = await freePort();",
        "  const child = spawn(process.execPath, [\"dist/server.js\"], {",
        "    env: { ...process.env, D3CODE_MOCK: \"0\", D3CODE_ALLOW_WRITES: \"0\", PORT: String(port), D3CODE_D3_COMMAND: \"cat\" },",
        "    stdio: [\"ignore\", \"pipe\", \"pipe\"],",
        "  });",
        "  try {",
        `    await waitForJson(\`http://127.0.0.1:\${port}/health\`);`,
        "    if (resources.length === 0) return;",
        `    const response = await fetch(\`http://127.0.0.1:\${port}/\${resources[0]}\`, {`,
        "      method: \"POST\",",
        "      headers: { \"content-type\": \"application/json\" },",
        "      body: JSON.stringify({ id: \"SMOKE\", attributes: {} }),",
        "    });",
        "    assert.equal(response.status, 500);",
        "    const body = await response.json();",
        "    assert.match(body.error, /mutation blocked/i);",
        "  } finally {",
        "    child.kill(\"SIGTERM\");",
        "  }",
        "});",
        "",
        "test(\"generated API denies D3 writes without a reviewed IDE access role\", async () => {",
        "  const port = await freePort();",
        "  const child = spawn(process.execPath, [\"dist/server.js\"], {",
        "    env: { ...process.env, D3CODE_MOCK: \"0\", D3CODE_ALLOW_WRITES: \"1\", PORT: String(port), D3CODE_D3_COMMAND: \"cat\" },",
        "    stdio: [\"ignore\", \"pipe\", \"pipe\"],",
        "  });",
        "  try {",
        `    await waitForJson(\`http://127.0.0.1:\${port}/health\`);`,
        "    if (resources.length === 0) return;",
        `    const response = await fetch(\`http://127.0.0.1:\${port}/\${resources[0]}\`, {`,
        "      method: \"POST\",",
        "      headers: { \"content-type\": \"application/json\" },",
        "      body: JSON.stringify({ id: \"SMOKE\", attributes: {} }),",
        "    });",
        "    assert.equal(response.status, 500);",
        "    const body = await response.json();",
        "    assert.match(body.error, /access denied/i);",
        "  } finally {",
        "    child.kill(\"SIGTERM\");",
        "  }",
        "});",
        "",
      ].join("\n"),
    },
  ]
}
